[package]
name = "rsudoas"
version = "1.0.0"
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
getopt = "1.1.3"
libc = "0.2.147"
nix = {version = "0.27.1", features = [
	"hostname",
]}
pwd-grp = "0.1.1"
rpassword = "7.3.1"
shadow = "0.0.1"
syslog-c = "0.1.3"
